name: Production

on:
    push: 
      paths:
        - 'web/**'
        - 'docker/NextJs/**'
      branches: [ master ]
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code Gdal Libraries
              uses: actions/checkout@v4
              
            - name: Install Node js
              uses: actions/setup-node@v4
              with:
                node-version: '18'

            - name: Install Packages and Build
              working-directory: web
              run: npm install && npm run build

    build:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Build Checkout
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}    

            - name: Build Image and Push
              run: |
                docker build -t shukishahapo-web -f docker/NextJs/Dockerfile web 
                docker tag shukishahapo-web:latest monyorojoseph/shukishahapo-web:latest
                docker push monyorojoseph/shukishahapo-web:latest
    
    deploy:
      runs-on: ubuntu-lates
      needs: build
      steps:
          - name: Deploy Web App
            uses: D3rHase/ssh-command-action@latest
            with:
              host: ${{ secrets.HOST }}
              port: ${{ secrets.PORT }}
              user: ${{ secrets.USER }}
              private_key: ${{ secrets.PRIVATE_KEY }}
              command: |
                cd shukishahapo/
                docker compose pull
                docker compose up --build -d


